POST  http://localhost:4001/api/contactUs
Content-Type: application/json

{
    "email": "test@gmail.com",
    "title": "React TS 4",
    "message": "React TS"        
}

###
POST  http://localhost:4001/api/contactUs/test-mail-service
Content-Type: application/json

###
POST  http://localhost:4001/api/contactUs/start-cronjob
Content-Type: application/json

{
    "cronJob": "17 17 * * *" 
}