POST  http://localhost:4000/api/posts
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFmZDVjNDQ2ZTQ1NTczMzhmNTNkYmYiLCJ1c2VybmFtZSI6Imdlb3JnZSIsImlhdCI6MTYzMTQ2MDk2MiwiZXhwIjoxNjMxNDYyNzYyfQ.n4ZwcMv-2qqgkfRbCif8GXqkFNcgdiucvOunlagFdcs
Content-Type: application/json

{
    "title": "React TS 4",
    "description": "React TS",
    "url": "google.com",
    "status": "TO LEARN"
}

###

GET  http://localhost:4000/api/posts
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFmZDVjNDQ2ZTQ1NTczMzhmNTNkYmYiLCJ1c2VybmFtZSI6Imdlb3JnZSIsImlhdCI6MTYzMTQ2MDk2MiwiZXhwIjoxNjMxNDYyNzYyfQ.n4ZwcMv-2qqgkfRbCif8GXqkFNcgdiucvOunlagFdcs

###
PUT  http://localhost:4000/api/posts/61208b0437f69642601e5d41
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFmZDZhZjNjNGJlYzcwZThlZjc5MDIiLCJ1c2VybmFtZSI6Imdlb3JnZTQiLCJpYXQiOjE2Mjk1MjM5MDcsImV4cCI6MTYyOTUyNTcwN30.pjETc6olahFe1zGxaLq1UDStaAhiuPtTquZRQY-zu18
Content-Type: application/json

{
    "title": "my first post fix",
    "description": "abc ",
    "url": "google2.com",
    "status": "LEARNING"
}

###
DELETE  http://localhost:4000/api/posts/61208b0437f69642601e5d41
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFmZDVjNDQ2ZTQ1NTczMzhmNTNkYmYiLCJ1c2VybmFtZSI6Imdlb3JnZSIsImlhdCI6MTYyOTU2MDUyNSwiZXhwIjoxNjI5NTYyMzI1fQ.JevFzL6c_zcI_EbadFTXxWkumqX8m_9C-xWlTaQySBk
